# Site settings
title: Jacob Quintero personal website
description: Jacob Quintero
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jacob Quintero
user_description: Currently intrested in Data Science projects and research
user_title: Mathematics and Computer Science Student
email: jquintero_02@arcadia.edu
twitter_username: https://twitter.com/@spiffyjacob
github_username:  https://github.com/jquintero-02

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
